<?php

    return[
            'hair transplant'   => 'HAIR TRANSPLANT',
            'hair transplant fue'   => 'FUE Hair Transplant',
            'hair transplant fue in albania'   => 'FUE Hair Transplant in Albania',
            'fue transplant description first'       => 'FUE hair transplant in Albania is a procedure that is quickly growing in popularity. FUE is a minimally invasive surgical hair restoration procedure that uses the FUT (follicular unit extraction) method which allows the transplant surgeon to extract hair follicles from the back of the head and insert them into your bald scalp areas. This in turn allows for faster results and less scarring than traditional strip harvesting techniques, which can leave patients with large scars. The Sapphire FUE is a minor surgical procedure, painless and you may not even feel like you’re having a surgery because it is minimally invasive.',
            'fue transplant description second'     => 'The FUE is performed by skilled surgeons who are experienced at performing this technique on patients with thinning or balding areas of the scalp, such as around temples or crowns. FUE surgery is safe and you won’t need anesthesia. We do not use total anesthetic solutions during your procedure—only local anesthesia will be administered before each session starts (which lasts about 1 hour). Results: The results are permanent, if performed correctly by an experienced plastic surgeon. There should never be any need for touch ups unless otherwise noted by the surgeon during post-surgery consultations. Aftercare instructions will be given beforehand too!',
            'if you are looking for hair treatment' => 'If you’re looking for a hair loss treatment that will deliver quick and long-lasting results, we offer the best Sapphire FUE hair transplant in Albania.',
            'does it hurt'                          => 'Does it hurt ?',
            'does it hurt answer'                   => 'Before the procedure commences, you will be treated with a local anesthetic, making FUT a painless and comfortable procedure. ',
            'how long does it take'                 => 'How long does the procedure take ?',
            'how long does answer'                  => 'Depending on the size of the area to be treated and the number of grafts that need to be transplanted, FUE can take between 4 and 8 hours.',
            'when i can see result'                 => 'When can i see results ?',
            'when i can see result answer'          => 'You can expect to start seeing the new hairs grow approximately 4-6 months after the treatment. This hair growth will continue to thicken over the first 10 to 15 months. As time passes, the hair will continue to grow in the same way as the hair in the donor area, thus creating a fuller, thicker head of hair.',
            'dhi in albania'                        => 'Direct Hair Transplant (DHI) in Albania',
            'dhi description'                       => 'During FUT, a surgeon cuts a strip of hair from the back of your scalp and extracts individual hair follicles. During FUE, a surgeon removes follicles directly from your scalp. In both surgeries, the follicles are implanted into balding parts of your scalp. Direct hair implantation (DHI) is a modification of the FUE technique created by the company DHI Global Medical Group. In FUE, a surgeon manually cuts channels in your scalp before implanting hair follicles. During DHI, they use a specialized penshaped tool that can do both at the same time. Let’s break down everything you need to know about DHI surgery. We’ll also compare it to FUT and FUE to help you decide which may be best for you.',
            'dhi vs fue and fut'                    => 'DHI vs. FUE and FUT hair transplant',
            'dhi fue and fut desc'                  => 'DHI, FUE, and FUT all involve taking follicles from one part of your scalp and implanting them into balding areas.',
            'fut hair transplant'                   => 'FUT Hair Transplant',
            'fut description'                       => 'During FUT surgery, a surgeon cuts a long and narrow strip of skin from the back of your scalp. Individual hair follicles are removed and implanted along your hairline. This method is usually the quickest and cheapest, but it can leave a long scar and hair transplant surgeons are moving away from this technique.',
            'both in dhi and fue'                   => 'Both in DHI and FUE surgeries, individual hair follicles are removed directly from your scalp and planted in the bolding area but there is a difference.',
            'dhi mini desc'                         => 'The DHI technique allows surgeons to make these incisions and implant hair at the same time. DHI and FUE avoid the long scar caused by FUT, however, these surgeries generally take longer and are more expensive.',
            'fue mini desc'                         => 'FUE is a two step process where a surgeon first manually cuts a series of canals in your scalp to insert the hair follicles, and second the insertion takes place.',
            'hair transplant for women'             => 'Hair Transplant for Women in Albania',
            'best hair for women'                   => 'Best Hair Transplant for Women in Tirana, Albania.',
            'best hair description'                 => 'There has been a great deal of research done into hair implants for women in recent years which has led to some amazing advances in medicine for women with these types of conditions. Hair transplantation is a safe and effective method of restoring hair loss in women. It involves the transplantation of healthy advanced follicles harvested from an area that has been shaved or depilated (such as the back of the head). The transplanted follicles will grow into new hairs which look natural and feel similar to those on your head. If you’re looking for an affordable and effective way to regain your healthy hair, female hair transplant in Albania is an excellent solution!',
            'question and answer'                   => 'Question & Answer',
            'what is female hair transplant'        => 'What is a female hair transplant?',
            'what is female hair transplant answer' => 'A hair transplant, also known as a follicular unit transplant, is a surgical procedure to move hair from one part of the body to another.
                                                        It can be used to treat thinning or baldness to improve one’s appearance and self-esteem.
                                                        The process involves removing hair follicles from one area of the body and implanting them in an area where it has fallen out due to injury or other causes.
                                                        There are two major transplant methods FUE and FUT which we explained in detail in the appropriate sections. ',
            'why do women make hair transplant'     => 'Why do women get hair transplants?',
            'why do women make hair transplant answer'=> 'Hair loss is not just a cosmetic problem, but it can affect your self-esteem and relationships. It also affects your social life, work life and overall quality of life. In addition to the physical pain of losing hair from the top of your head or from other parts of your body (like eyebrows), there are many psychological effects that come along with having thinning hair. ',
            'how last recovery in women'            => 'How long does the recovery period of a womans hair transplant last?',
            'how last recovery in women answer'     => 'The recovery period of a woman’s hair transplant depends on the number of transplants you’ve done. The first two days after your surgery are considered to be “the burn phase,” which is when your body is healing from the trauma of having large amounts of tissue removed from its own body. Within this timeframe, you may experience some swelling and bruising around your incisions; however, this should settle out within a few days’ time. After that initial stage (and for up to three weeks), it’s important not to sit still or sleep more than usual as this can cause further damage to your head area and lead to pain later on in your recovery process. You should also avoid exercise or heavy lifting until all swelling has subsided completely—this means no running marathons just yet! During this time frame also expect some discomfort due to being unable to take care of yourself properly so try to take advantage whenever possible by curling up in your blanket with some good books or a TV show.',
                                                        
        ]   
?>